{% set name = "shaffle" %}
{% set version = "0.0.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7cc0f966e6dea0be16ef70ff5f08b34f1c8dc8fe4e5eb99e62552c2e2febfe9f

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - shaffle
  commands:
    - pip check

about:
  home: https://github.com/haochuanwei/shaffle
  license: MIT
  license_file: LICENSE
  summary: Map hash-ables to pseudo-random numbers.
  dev_url: https://github.com/haochuanwei/shaffle

extra:
  recipe-maintainers:
    - haochuanwei
